In [29]:
import pandas as pd

data = pd.read_csv("gapminder.csv")

#gby = data.groupby("country")
 
sorted_list = data.sort_values('lifeExp',ascending = False).head(5)

#sorted_list.to_csv("result11.csv")  

resultdata = pd.read_csv("result11.csv")
resultdata

,Unnamed: 0,country,year,pop,continent,lifeExp,gdpPercap
0,803,Japan,2007,127467972.0,Asia,82.603,31656.06806
1,671,Hong Kong China,2007,6980412.0,Asia,82.208,39724.97867
2,802,Japan,2002,127065841.0,Asia,82.000,28604.59190
3,695,Iceland,2007,301931.0,Europe,81.757,36180.78919
4,1487,Switzerland,2007,7554661.0,Europe,81.701,37506.41907